### PR TITLE
Apply webpack-dev-server 4.0 changes

### LINKED ISSUE #2653: [6.*] npx mix watch --hot gives Unknown argument
-   Laravel Mix Version: 6.0.0-beta.15 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.1
-   NPM Version (`npm -v`): 6.14.8
-   OS: windows

### Description:
I get this error upon running the command
> mix watch --hot
[webpack-cli] Unknown argument: --inline
[webpack-cli] Unknown argument: --disable-host-check

### Steps To Reproduce:
npm install laravel-mix@6.0.0-beta.15 -D
Then npx mix watch --hot

### PR DESCRIPTION
**Pull request by soilSpoon**
This PR resolve #2653

## Reference
[webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0)

### CODE REVIEW

**Comment by thecrypticace** [comment]
From what I can tell this looks good to me. You can ignore the windows failure right now. Something is causing weird issues there that I have to look into.

I plan to add an integration test for the webpack-cli so this could've been caught earlier.

File: bin/cli.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ function commandScript(cmd, opts) {
 
         return 'npx webpack --watch';
     } else if (cmd === 'watch' && opts.hot) {
-        return 'npx webpack serve --hot --inline --disable-host-check';
+        return 'npx webpack serve --hot';
```
Comment (soilSpoon) [inline bin/cli.js:94]: The `hot` option is left over because it checks if it is included in `process.argv`.
Let me know if there is a better way

Comment (thecrypticace) [reply bin/cli.js:94]: We should probably ask webpack itself if it's running via HMR. I'll take a look today to see how to do that.

Comment (oza75) [reply bin/cli.js:94]: It will also be good if we can enable the webpack-dev-server https. I tried this `npx mix --hot --https` but got an` unknow option` error. it would be nice if we weren't limited to the options defined by laravel-mix

Comment (thecrypticace) [reply bin/cli.js:94]: We're not! You can pass arbitrary options after `--` like so `npx mix --hot -- --https`

Comment (oza75) [reply bin/cli.js:94]: Thanks @thecrypticace. it worked but when I reload my page I get net::ERR_CERT_AUTHORITY_INVALID http error. Maybe I'm doing something wrong

Comment (thecrypticace) [reply bin/cli.js:94]: That's because webpack's https support uses a self-signed certificate by default. If you want to customize that you'll have to customize the webpack config.

**Comment by JeffreyWay** [comment]
Thanks for this @soilSpoon. I'll go ahead and merge this so it can go out as part of the next beta I'm about to release.
